### ISSUE TITLE
Order with reprojection to aea

### ISSUE THREAD

**Issue by loicdtx** [USGS-EROS/espa-api#109]
I placed an order with the following json, but I get a note for every scene saying `Error transforming product, check projection parameters`. I can't figure out what's wrong with the parameters I put. I tried swapping sp1 and sp2 (which one is south or north?), but got the same error.
Any idea?
```json
{
  "image_extents": {
    "units": "dd",
    "west": -72.11,
    "east": -71.86,
    "north": 1.66,
    "south": 1.41
  },
  "projection": {
    "aea": {
      "standard_parallel_1": 2,
      "central_meridian": -72,
      "datum": "wgs84",
      "latitude_of_origin": 1.5,
      "standard_parallel_2": 1,
      "false_northing": 0,
      "false_easting": 0
    }
  },
  "format": "gtiff",
  "resampling_method": "nn",
  "note": "colombia reprex 2017 Guaviare",
  "olitirs8_collection": {
    "inputs": [
      "LC08_L1TP_006059_20170111_20170311_01_T1",
      "LC08_L1TP_006059_20170228_20170316_01_T1",
      "LC08_L1TP_006059_20170316_20170328_01_T1",
      "LC08_L1TP_006059_20170519_20170525_01_T2",
      "LC08_L1GT_006059_20170604_20170616_01_T2",
      "LC08_L1TP_006059_20171010_20171024_01_T1",
      "LC08_L1TP_006059_20171026_20171107_01_T1",
      "LC08_L1GT_006059_20171111_20171121_01_T2"
    ],
    "products": [
      "sr",
      "pixel_qa",
      "sr_ndvi",
      "sr_ndmi"
    ]
  }
}
```

**Comment by saeedarab** [comment]
Hi @loicdtx 
sp1 is the south standard parallel and sp2 is the north one. But ESPA automatically corrects it if they are entered in the wrong box. 
There is a minor issue in transforming your requested area of interest (AOI) into the Albers projection system you specified. The issue is being investigated but before the problem gets resolved, you can re-submit your scenes without clipping (not using "modify image extent"), or using the Albers coordinates of your AOI in meters (instead of decimal degrees).

**Comment by saeedarab** [comment]
The reprojection issue has been fixed and successfully tested.
