### ISSUE TITLE
Check if a product is available or not

### ISSUE THREAD

**Issue by athanasis** [USGS-EROS/espa-api#43]
Hi, 

Based on the espa-api, the following lists the available output products for the supplied input:

curl --get --user username:password https://espa.cr.usgs.gov/api/v0/available-products/LC80270292015233LGN00

If I change the product id and ask for a product which is not available yet, why does the api not return a "not implemented" message? 

For example, the following should return a "not implemented", because I ask for a product from year 2017. 

curl --get --user username:password https://espa.cr.usgs.gov/api/v0/available-products/LC80270292017233LGN00

Why does it not now show this message? How can I check if a product is not available yet?

**Comment by caustin-usgs** [comment]
Thats because the available-products endpoint isn't that intelligent.  It simply checks whats possible for a  Landsat 8 based product.  You bring up a good point though, and its something we'll discuss adding.

Product availability is validated on order submission though, and if you submitted an order with that scene, you'd be told so.
